import Feed from "@/Components/Feed";
import Header from "@/Components/Header";
import Modal from "@/Components/Modal";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
        <Head>
          <title>Instagram</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Feed />
        <Modal />
      </div>
    </>
  );
}
